### ISSUE TITLE
Add back button to the interaction view.

### ISSUE THREAD

**Issue by michbur** [KotulskaLab/AmyloGraph#29]
The back button should guide the user back to the table or the graph.

**Comment by ErdaradunGaztea** [comment]
Honestly, I'm not enthusiastic towards this solution. The user should already know about being able to switch between tabs, since there is a table accessible only this way, with no other link from the graph. Adding back button to only one panel might be misleading and surely would look strange.

There are things we can improve, though. For starters, I'd recommend hiding "Interaction" tab until the user clicks on a "Details" button. We could possibly also remove "Interaction" tab upon switching to any other, but I suppose that the user might want to switch between the panels freely, going back to the interaction they found. Thus, possibly a "Close" button -- instead of "Back" -- could be placed. This might solve the problem of users clicking back button on their browsers due to confusion.

Also, I'd make the tab bar more pronounced so that the user notices it more easily.
