### ISSUE TITLE
Add cookies information

### ISSUE THREAD

**Issue by michbur** [KotulskaLab/AmyloGraph#62]

**Comment by michbur** [comment]
It is still in progress. I followed instructions from https://github.com/DataScienceScotland/shiny_cookies and added https://github.com/KotulskaLab/AmyloGraph/blob/main/R/render_ga.R but it doesn't seem to work :(

**Comment by ErdaradunGaztea** [comment]
The script from `www/cookie_control_config.js` and the two scripts included in `render_ga()` should go all either in `<head>` or `<body>`, right now they are split into both and thus `CookieControl` in the first script is undefined by the time of its execution, since the other two scripts execute later.

**Comment by michbur** [comment]
No progress - we will switch to a different technology.
